version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Previous Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
build:
  project: tpm2-tss.sln
  parallel: false
  verbosity: normal
